---
- hosts: localhost
  gather_facts: no

  vars_files: 
    - wireless.yml
  
  tasks:
    - name: Read SSIDs
      cisco.meraki.meraki_mr_ssid:
        auth_key: "{{ meraki_key }}"
        org_name: "{{ Org_Name }}"
        net_name: "{{ Net_Name }}"
        state: query
      delegate_to: localhost