---
- hosts: localhost
  gather_facts: yes

  # defined vars needed:
  # - description  --> Should include commit id from GitHub repo
  # - description_short
  # - change_req_template
  # these should come from a previous playbook/workflow step

  vars:
    description_short: "Update SSIDs - From GitHub Repo {{ tower_webhook_payload.repository.name | default('TEST') }}"
    description: |
      Update SSIDs. Triggered by GitHub event in repository {{ tower_webhook_payload.repository.name | default('TEST') }}
      Short commit id: {{ tower_webhook_payload.after | default('TEST COMMIT ID SHORT') }}
      Full commit id: {{ tower_webhook_payload.after[:7] | default('TEST COMMIT ID') }}
      Commit by: {{ tower_webhook_payload.head_commit.author.name | default('TEST NAME') }}

  tasks:
    - name: Create Change Request on snow
      servicenow.itsm.change_request:
        state: new
        type: standard
        short_description: "{{ description_short | default('Demo change request') }}"
        description: "{{ description | default('This is just a Demo Change Request created by Ansible') }}"
        category: network
        other:
      register: change_req

    - name: set value of new change request'
      set_fact:
        change_req_id: "{{ change_req.record.number }}"

    - name: Change state Change Request on snow - schedule
      servicenow.itsm.change_request:
        state: scheduled
        type: standard
        number: "{{ change_req_id }}"
        assignment_group: Hardware
        other: 
          expected_start: "{{ ansible_date_time.date }}"
      register: change_req

    - name: Change state Change Request on snow - implement
      servicenow.itsm.change_request:
        state: implement
        type: standard
        number: "{{ change_req_id }}"
        assignment_group: Hardware
      register: change_req

    - name: Change state Change Request on snow - review
      servicenow.itsm.change_request:
        state: review
        type: standard
        number: "{{ change_req_id }}"
        assignment_group: Hardware
      register: change_req

    - name: Save info for next steps
      set_stats: 
        data:
          change_req_id: "{{ change_req_id }}"
