---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: Close Change Request on SNow
      servicenow.itsm.change_request:
        state: closed
        number: "{{ change_req_id }}"
        assignment_group: Hardware
        close_code: successful
        close_notes: |
          {{ applied_changes | to_nice_json}}
