---
- hosts: localhost
  gather_facts: no 
  
  vars_files: 
    - firewall.yml
  
  tasks:
    - name: update L7 Firewall Rules
      cisco.meraki.meraki_mx_l7_firewall:
        auth_key: "{{ meraki_key }}"
        org_name: "{{ Org_Name }}"
        net_name: "{{ Net_Name }}"
        state: "{{ item.state | default('present') }}"
        rules: "{{ rules }}"

    - name: Save info for next steps
      set_stats: 
        data:
          change_req_id: "{{ change_req_id }}"
          applied_changes: "{{ applied_changes }}"
