---
- hosts: localhost
  gather_facts: no 
  
  vars: 
    file_url: https://raw.githubusercontent.com/pseguel-redhat/rhsummitdemo_firewall/main/firewall.yml
  
  tasks:
    - name: Get current file
      set_fact:
        firewall: "{{ src | from_yaml }}"
      vars:
        src: "{{ lookup('url', file_url, split_lines='no') }}"

    - name: update L7 Firewall Rules
      cisco.meraki.meraki_mx_l7_firewall:
        auth_key: "{{ meraki_key }}"
        org_name: "{{ firewall.Org_Name }}"
        net_name: "{{ firewall.Net_Name }}"
        state: "{{ item.state | default('present') }}"
        rules: "{{ firewall.rules }}"
      register: applied_changes

    - name: Save info for next steps
      set_stats: 
        data:
          change_req_id: "{{ change_req_id }}"
          applied_changes: "{{ applied_changes }}"
